chore: set prettier
hiromu-koizumi/koizumi-blog pull request #32
Opened 2023-02-09 22:44 UTC by hiromu-koizumi

close #15

2023-02-10 01:06 UTC, piro0919 requested changes

2023-02-10 01:06 UTC, piro0919 commented on package.json
> +    "prettier": "2.8.4"
[imo]

Next v13 からは devDependencies は使わない方向になったので dependencies にまとめてほしいですね。

2023-02-11 09:09 UTC, hiromu-koizumi commented on package.json
> +    "prettier": "2.8.4"
ご指摘ありがとうございます！
next側でデプロイに必要なファイルを判定してくれるので不要なんですね。知りませんでした！

参照
https://github.com/vercel/vercel/discussions/9013

2023-02-11 15:55 UTC, piro0919 approved these changes
LGTM 👍

2023-02-12 00:57 UTC, merged